%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%                import data from .txt file
%
%   this function takes as input the .txt file containing raw extracellular
%   recordings generated by MC_Rack and imports the data, saving the names
%   of the electrodes and their subsequent data into a temporary
%   destination folder
%
%   fpath: the location and name of the .txt file
%   output_name: the name of the file to output
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
function import_txt(fpath,output_name)

disp('started data import')
fil = [fpath '.txt'];
data = importdata(fil);

% extract information about the electrode names
eheader = data.textdata(2,1);
enom = textscan(eheader{1},'%s');
c = 1;
electrodes = {};
for e = 3:2:length(enom{1})
    electrodes{c} = enom{1}{e};
    c = c+1;
end

disp('data import complete')

save(output_name,'data','electrodes')

disp('output saved')

end